#! /bin/sh

# Set up multimonitors (in this case 2)
MONITORS=($(xrandr --listmonitors | awk ' NR > 1 {ORS=" "; print $NF }'))

xrandr --output ${MONITORS[0]} --auto
xrandr --output ${MONITORS[1]} --auto --left-of ${MONITORS[0]}

# Set up bspwm
bspc monitor ${MONITORS[0]} -d 7 8 9 10 11 12
bspc monitor ${MONITORS[1]} -d 1 2 3 4 5 6

bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Color settings
bspc config focused_border_color "#536AB5"
bspc config normal_border_color "#222D32"
bspc config border_width         1

bspc config focus_follows_pointer true

# Set up background
if [ -f ~/Documents/wallpapers/bg.jpg]
then
    feh --bg-fill ~/Documents/wallpapers/bg.jpg
else
    feh --bg-fill ~/.config/bspwm/bg.jpg
fi

# Initialize flashfocus
if pgrep -x "flashfocus" > /dev/null; then
    kill $(pgrep "flashfocus")
    wait $(pgrep "flashfocus")
else
    flashfocus &
fi

# Initialize picom (Compton alternative)
if pgrep -x "picom" > /dev/null; then
    kill $(pgrep "picom")
    wait $(pgrep "picom")
else
    picom -b
fi

# Initialize xidlehookl
if pgrep -x "xidlehook" > /dev/null; then
    kill $(pgrep "xidlehook")
    wait $(pgrep "xidlehook")
else
    xidlehook  --not-when-fullscreen --not-when-audio \
        --timer primary 600 "betterlockscreen -l dim" "" \
        --timer normal 900 "systemctl suspend" "" &
fi

# Launch polybar
$HOME/.config/polybar/launch.sh

# Launch sxhkd
sxhkd &
