#! /bin/sh

sxhkd &

MONITORS=($(xrandr --listmonitors | awk ' NR > 1 {ORS=" "; print $NF }'))

xrandr --output ${MONITORS[0]} --auto
xrandr --output ${MONITORS[1]} --auto --left-of ${MONITORS[0]}

feh --bg-fill ~/.config/bspwm/bg.jpg

if pgrep -x "flashfocus" > /dev/null; then
    kill $(pgrep "flashfocus")
    wait $(pgrep "flashfocus")
else
    flashfocus &
fi

if pgrep -x "compton" > /dev/null; then
    kill $(pgrep "compton")
    wait $(pgrep "compton")
else
    compton -b
fi

if pgrep -x "xidlehook" > /dev/null; then
    kill $(pgrep "xidlehook")
    wait $(pgrep "xidlehook")
else
    xidlehook  --not-when-fullscreen --not-when-audio \
        --timer primary 600 "betterlockscreen -l dim" "" \
        --timer normal 900 "systemctl suspend" "" &
fi

bspc monitor ${MONITORS[0]} -d 7 8 9 10 11 12
bspc monitor ${MONITORS[1]} -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
