#! /bin/sh

# Set up multimonitors (in this case 2)
MONITORS=($(xrandr --listmonitors | awk ' NR > 1 {ORS=" "; print $NF }'))

xrandr --output ${MONITORS[0]} --auto
xrandr --output ${MONITORS[1]} --auto --right-of ${MONITORS[0]}

# Set up bspwm
bspc monitor ${MONITORS[0]} -d 1 2 3 4 5 6
bspc monitor ${MONITORS[1]} -d 7 8 9 10 11 12

bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# Color settings
bspc config focused_border_color "#536AB5"
#bspc config active_border_color "#222D32"
bspc config normal_border_color "#222D32"
bspc config border_width         2

bspc config focus_follows_pointer true

# Set up background
if [ -f ~/Documents/wallpapers/bg.jpg ]
then
    nitrogen --force-setter=xinerama --head=0 --set-zoom-fill ~/Documents/wallpapers/bg.jpg
    nitrogen --force-setter=xinerama --head=1 --set-zoom-fill ~/Documents/wallpapers/bg.jpg
else
    nitrogen --force-setter=xinerama --head=0 --set-zoom-fill ~/Documents/github/dotfiles/arch/bspwm/bg.jpg
    nitrogen --force-setter=xinerama --head=1 --set-zoom-fill ~/Documents/github/dotfiles/arch/bspwm/bg.jpg
fi

flashfocus &
picom --vsync --daemon

## Initialize xidlehook
if pgrep -x "xidlehook" > /dev/null; then
    kill $(pgrep "xidlehook")
    wait $(pgrep "xidlehook")
else
    xidlehook  --not-when-fullscreen --not-when-audio \
        --timer 600 "betterlockscreen -l dim" "" \
        --timer 900 "systemctl suspend" "" &
fi

# Launch polybar
$HOME/.config/polybar/launch.sh

# Launch sxhkd
sxhkd &

# Start polkit agent
lxpolkit &
