#!/bin/sh

# Go to root directory
cd ~ || exit

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `install.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if [ "$(uname)" = "Darwin" ]; then
    # Install brew
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    # Install git
    brew install git
elif [ -f /etc/arch-release ]; then
    # Install git
    sudo pacman -S git --noconfirm
fi

# Setup git
git -C ~/Documents/github/dotfiles config user.name "Shourai"
git -C ~/Documents/github/dotfiles config user.email "10200748+Shourai@users.noreply.github.com"

# Clone respository
git clone https://github.com/Shourai/dotfiles.git ~/Documents/github/dotfiles

# Change git repo from https to SSH
git -C ~/Documents/github/dotfiles remote set-url origin git@github.com:Shourai/dotfiles.git

# Wait for a little while before continuing
echo "We are now installing the needed packages and setting the desired configuration."
sleep 3

if [ "$(uname)" = "Darwin" ]; then
    # Install brew packages
    sh ~/Documents/github/dotfiles/macOS/brew.sh
elif [ -f /etc/arch-release ]; then
    # Install pacman packages
    sh ~/Documents/github/dotfiles/arch/packages.sh
fi

# Link dotfiles
sh ~/Documents/github/dotfiles/macOS/dotfiles.sh

# Change shell to zsh
sh ~/Documents/github/dotfiles/macOS/shell.sh

# macOS changes
if [ "$(uname)" = "Darwin" ]; then
    sh ~/Documents/github/dotfiles/macOS/macOS.sh
fi

# Additional installations
echo "Do you wish to install additional python packages?"
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then
    sh ~/Documents/github/dotfiles/macOS/miscellaneous.sh
else
    echo "Skipping python packages"
fi

echo "Success! Reboot the machine for the changes to take effect"
