#!/bin/bash

# Go to root directory
cd ~ || exit

# Ask for the administrator password upfront
if [ "$(uname)" = "Darwin" ]; then
    sudo -v
fi

# Keep-alive: update existing `sudo` time stamp until `install.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if [ "$(uname)" = "Darwin" ]; then
    # Install brew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Install git
    brew install git
elif [ -f /etc/arch-release ]; then
    # Install git
    sudo pacman -S git --noconfirm
fi


# Clone respository
git clone https://github.com/Shourai/dotfiles.git ~/Documents/github/dotfiles

# Setup git
git -C ~/Documents/github/dotfiles config user.name "Shourai"
git -C ~/Documents/github/dotfiles config user.email "10200748+Shourai@users.noreply.github.com"

# Change git repo from https to SSH
git -C ~/Documents/github/dotfiles remote set-url origin git@github.com:Shourai/dotfiles.git

# Wait for a little while before continuing
echo "We are now installing the needed packages and setting the desired configuration."

if [ "$(uname)" = "Darwin" ]; then
    # Install brew packages
    bash ~/Documents/github/dotfiles/macOS/brew.sh
elif [ -f /etc/arch-release ]; then
    # Install pacman packages
    bash ~/Documents/github/dotfiles/arch/packages.sh
fi

# Link dotfiles
bash ~/Documents/github/dotfiles/arch/dotfiles.sh

# Change shell to zsh
if [ -f /etc/arch-release ]; then
    chsh -s "$(command -v zsh)"
fi

# Cleanup
echo "Doing cleanup"
if [ "$(uname)" = "Darwin" ]; then
    echo "Brew cleanup"
    brew cleanup
elif [ -f /etc/arch-release ]; then
    echo "Cleaning up pacman cache"
    sudo pacman -Sc --noconfirm
fi

echo "Success! Reboot the machine for the changes to take effect"
