#! /bin/sh

sxhkd &

xrandr --output VGA1 --auto --output HDMI1 --auto --left-of VGA1

killall compton && compton &
killall flashfocus && flashfocus &

bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor VGA1 -d 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
