#!/bin/bash

# Go to root directory
cd ~

apt install git -y
git config --global user.name "Shourai"
git config --global user.email "10200748+Shourai@users.noreply.github.com"
git config --global credential.helper cache

# Clone respository
git clone https://github.com/Shourai/dotfiles.git ~/Documents/github/dotfiles

# Wait for a little while before continuing
echo "We are now installing the needed packages and setting the desired configuration."
sleep 1

sh ~/Documents/github/dotfiles/android/packages.sh

# Link dotfiles
sh ~/Documents/github/dotfiles/macOS/dotfiles.sh

# Change shell to zsh
sh ~/Documents/github/dotfiles/macOS/shell.sh

echo "Success! Reboot the machine for the changes to take effect"
