
[colors.primary]
background = "#272727"
foreground = "#ffffff"

[font]
size = 11.0

[font.bold]
family = "Jet Brains Mono"

[font.normal]
family = "Jet Brains Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000

[window]
opacity = 0.6

[window.padding]
x = 5
y = 5

[general]
import = ["/home/serenity/.config/alacritty/themes/theme.toml"]
