# Set the typematic delay and rate for an active x server
xset r rate 200 100

# Remap caps to control
setxkbmap -option 'ctrl:nocaps,altwin:swap_lalt_lwin'

# Execute i3 windows manager
exec bspwm

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
