# Set the typematic delay and rate for an active x server
xset r rate 200 100

# Remap caps to control
setxkbmap -option 'ctrl:nocaps,altwin:swap_lalt_lwin'

# Execute i3 windows manager
exec bspwm

# Start gnome keyring daemon
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# From Archwiki note
# Note: At the very least, ensure that the last if block in /etc/X11/xinit/xinitrc is present in your ~/.xinitrc file to ensure that the scripts in /etc/X11/xinit/xinitrc.d are sourced.

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
