# ----------------------------------------
# - Platform detection                   -
# ----------------------------------------

if [[ "$(uname)" = "Darwin" ]]; then
  export IS_DARWIN=1
elif [ -f /etc/arch-release ]; then
  export IS_ARCH=1
fi

# ----------------------------------------
# - Environmental variables              -
# ----------------------------------------

# Set XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Set Editor
export EDITOR="nvim"
export VISUAL="nvim"

# less
export LESSHISTFILE=-

# eza
export EZA_COLORS='xx=37'

# SSH_AUTH_SOCK for 1Password and bitwarden
if [[ "$(uname)" = "Darwin" ]]; then
  # Check if the Bitwarden socket file exists
  if [[ -S "$HOME/.bitwarden-ssh-agent.sock" ]]; then
    export SSH_AUTH_SOCK="$HOME/.bitwarden-ssh-agent.sock"
  else
    export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  fi
else
  # Linux fallback
  export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
fi
